package fastpdv.GUI;

import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author devguilara
 */
public class DashboardGUI extends javax.swing.JFrame {
    private JMenu jmenuSair;    /**
     * Creates new form DashboardGUI
     */
    public DashboardGUI() {
        setResizable(false);
        initComponents(); 
        setLocationRelativeTo(null);


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmenuCaixa = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmenuVenda = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmenuCadastros = new javax.swing.JMenu();
        jmenuProdutos = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jmenuCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jmenuFornecedor = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jmenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jmenuCaixa.setText("Caixa");

        jMenuItem2.setText("Abrir Caixa");
        jmenuCaixa.add(jMenuItem2);

        jMenuItem3.setText("Fechar Caixa");
        jmenuCaixa.add(jMenuItem3);

        jMenuBar2.add(jmenuCaixa);

        jmenuVenda.setText("Venda");

        jMenuItem4.setText("Nova Venda");
        jmenuVenda.add(jMenuItem4);

        jMenuItem5.setText("Cancelar Venda");
        jmenuVenda.add(jMenuItem5);

        jMenuBar2.add(jmenuVenda);

        jmenuCadastros.setText("Cadastros");

        jmenuProdutos.setText("Produtos");

        jMenuItem6.setText("Adicionar Produto");
        jmenuProdutos.add(jMenuItem6);

        jMenuItem7.setText("Editar Produto");
        jmenuProdutos.add(jMenuItem7);

        jmenuCadastros.add(jmenuProdutos);

        jmenuCliente.setText("Cliente");

        jMenuItem1.setText("Adicionar Cliente");
        jmenuCliente.add(jMenuItem1);

        jMenuItem8.setText("Editar Cliente");
        jmenuCliente.add(jMenuItem8);

        jmenuCadastros.add(jmenuCliente);

        jmenuFornecedor.setText("Fornecedor");
        jmenuFornecedor.setToolTipText("");

        jMenuItem9.setText("Cadastrar Fornecedor");
        jmenuFornecedor.add(jMenuItem9);

        jMenuItem10.setText("Editar Fornecedor");
        jmenuFornecedor.add(jMenuItem10);

        jmenuCadastros.add(jmenuFornecedor);

        jMenuBar2.add(jmenuCadastros);

        jMenu1.setText("Relatorios");

        jMenuItem11.setText("Relatorio de Vendas");
        jMenu1.add(jMenuItem11);

        jMenuBar2.add(jMenu1);

        jmenuExit.setText("Sair");
        jmenuExit.setAlignmentX(200.0F);
        jmenuExit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jmenuExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jmenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenuExitMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmenuExit);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuExitMouseClicked
        // TODO add your handling code here:
        btnMenuSair();
    }//GEN-LAST:event_jmenuExitMouseClicked

     private void btnMenuSair() {
        int resposta = JOptionPane.showConfirmDialog(
                this, 
                "Deseja mesmo sair do sistema?", 
                "Sair", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE
        );

        if (resposta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmenuCadastros;
    private javax.swing.JMenu jmenuCaixa;
    private javax.swing.JMenu jmenuCliente;
    private javax.swing.JMenu jmenuExit;
    private javax.swing.JMenu jmenuFornecedor;
    private javax.swing.JMenu jmenuProdutos;
    private javax.swing.JMenu jmenuVenda;
    // End of variables declaration//GEN-END:variables
}
